version: '3'

services:
  rainbowbot:
    build:
      context: .
    environment:
      TOKEN: ${TOKEN}
      DBURI: ${DBURI}
      NODE_ENV: ${NODE_ENV}
      MASTER_GUILD: ${MASTER_GUILD}
      TOPGG_TOKEN: ${TOPGG_TOKEN}
      OSU_API_KEY: ${OSU_API_KEY}
      DATA_DIR: /home/rainbowbot/data
      LOGS_DIR: /home/rainbowbot/logs
      ADMIN_ID: ${ADMIN_ID}
      PROM_PFX: ${PROM_PFX}
    volumes:
      - ./data:/home/rainbowbot/data
      - ./logs:/home/rainbowbot/logs