# This workflow will run tests using node

name: Try Build TS Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: sudo apt install -y graphicsmagick
      - run: |
          if [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - run: npm run build